// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSQCz1lfnGa3-befvLjKwOVaO8kwrApoo',
    appId: '1:916579666383:web:9b6ebfba0a48b6be9faaba',
    messagingSenderId: '916579666383',
    projectId: 'login-911',
    authDomain: 'login-911.firebaseapp.com',
    storageBucket: 'login-911.appspot.com',
    measurementId: 'G-6Y1N7R0189',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4p9vjzvBihGyEPQtm9qRPimFz63KkJDU',
    appId: '1:916579666383:android:e7129693bafa0f979faaba',
    messagingSenderId: '916579666383',
    projectId: 'login-911',
    storageBucket: 'login-911.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1DAQvvwlGs-nB-VTqUx_V5GP5MKFrO5Y',
    appId: '1:916579666383:ios:b0934b0dfe278a629faaba',
    messagingSenderId: '916579666383',
    projectId: 'login-911',
    storageBucket: 'login-911.appspot.com',
    iosClientId: '916579666383-8m9oe6pls6rhpa571tmgph23hi95s216.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled1',
  );
}
